#!/bin/bash

# Optional: Turn on ftrace to see the functions being executed.
sudo sysctl kernel.ftrace_enabled=1

sudo touch /debug/tracing/trace

# Enable specific functions to be traced.
echo sys_nanosleep hrtimer_interrupt > /debug/tracing/set_ftrace_filter

cat /debug/tracing/set_ftrace_filter

# Specify what tracer we want.
echo function > /debug/tracing/current_tracer

# Start tracing.
echo 1 > /debug/tracing/tracing_enabled

# Do something.
usleep 1

# Stop tracing.
echo 0 > /debug/tracing/tracing_enabled

# View the trace.
cat /debug/tracing/trace | head