
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '%\r\x93\xc6\xcf\x18\x0b\x16\x11\xa8\x7fF=\x9cJ*'
    
_lr_action_items = {'COLON':([2,],[3,]),'NAME':([0,],[2,]),'$end':([1,3,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'target_defn':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> target_defn","S'",1,None,None,None),
  ('target_defn -> NAME COLON','target_defn',2,'p_target_defn','../../ipymake/makefileparser.py',211),
  ('config_defn -> topdict_list','config_defn',1,'p_config_defn','../../ipymake/makefileparser.py',220),
  ('topdict_list -> topdict_list topdict_defn','topdict_list',2,'p_topdict_list1','../../ipymake/makefileparser.py',227),
  ('topdict_list -> topdict_defn','topdict_list',1,'p_topdict_list2','../../ipymake/makefileparser.py',232),
  ('topdict_list -> empty','topdict_list',1,'p_topdict_list3','../../ipymake/makefileparser.py',236),
  ('topdict_defn -> LEFT_ANGLE NAME RIGHT_ANGLE dict_elem_list','topdict_defn',4,'p_topdict_defn','../../ipymake/makefileparser.py',243),
  ('dict_defn -> LEFT_BRACE dict_elem_list RIGHT_BRACE','dict_defn',3,'p_dict_defn','../../ipymake/makefileparser.py',250),
  ('dict_elem_list -> dict_elem_list dict_member_defn','dict_elem_list',2,'p_dict_elem_list1','../../ipymake/makefileparser.py',257),
  ('dict_elem_list -> dict_member_defn','dict_elem_list',1,'p_dict_elem_list2','../../ipymake/makefileparser.py',262),
  ('dict_elem_list -> empty','dict_elem_list',1,'p_dict_elem_list3','../../ipymake/makefileparser.py',266),
  ('dict_member_defn -> NAME EQUAL data_defn','dict_member_defn',3,'p_dict_member_defn','../../ipymake/makefileparser.py',270),
  ('list_defn -> LEFT_SQUARE list_elem_list RIGHT_SQUARE','list_defn',3,'p_list_defn','../../ipymake/makefileparser.py',278),
  ('list_elem_list -> list_elem_list COMMA data_defn','list_elem_list',3,'p_list_elem_list_1','../../ipymake/makefileparser.py',282),
  ('list_elem_list -> list_elem_list data_defn','list_elem_list',2,'p_list_elem_list_4','../../ipymake/makefileparser.py',289),
  ('list_elem_list -> data_defn','list_elem_list',1,'p_list_elem_list_2','../../ipymake/makefileparser.py',296),
  ('list_elem_list -> empty','list_elem_list',1,'p_list_elem_list_3','../../ipymake/makefileparser.py',303),
  ('tuple_defn -> NAME LEFT_PAREN dict_elem_list RIGHT_PAREN','tuple_defn',4,'p_tuple_defn','../../ipymake/makefileparser.py',311),
  ('data_defn -> NAME','data_defn',1,'p_data_defn','../../ipymake/makefileparser.py',318),
  ('data_defn -> NUMBER','data_defn',1,'p_data_defn','../../ipymake/makefileparser.py',319),
  ('data_defn -> string','data_defn',1,'p_data_defn','../../ipymake/makefileparser.py',320),
  ('data_defn -> tuple_defn','data_defn',1,'p_data_defn','../../ipymake/makefileparser.py',321),
  ('data_defn -> list_defn','data_defn',1,'p_data_defn','../../ipymake/makefileparser.py',322),
  ('data_defn -> dict_defn','data_defn',1,'p_data_defn','../../ipymake/makefileparser.py',323),
  ('string -> STRING_LITERAL','string',1,'p_string','../../ipymake/makefileparser.py',327),
  ('empty -> <empty>','empty',0,'p_empty','../../ipymake/makefileparser.py',331),
]
