#line 2 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.c"

#line 4 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer configfile_create_buffer
#define yy_delete_buffer configfile_delete_buffer
#define yy_flex_debug configfile_flex_debug
#define yy_init_buffer configfile_init_buffer
#define yy_flush_buffer configfile_flush_buffer
#define yy_load_buffer_state configfile_load_buffer_state
#define yy_switch_to_buffer configfile_switch_to_buffer
#define yyin configfilein
#define yyleng configfileleng
#define yylex configfilelex
#define yylineno configfilelineno
#define yyout configfileout
#define yyrestart configfilerestart
#define yytext configfiletext
#define yywrap configfilewrap
#define yyalloc configfilealloc
#define yyrealloc configfilerealloc
#define yyfree configfilefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE configfilerestart(configfilein  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int configfileleng;

extern FILE *configfilein, *configfileout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up configfiletext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up configfiletext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via configfilerestart()), so that the user can continue scanning by
	 * just pointing configfilein at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when configfiletext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int configfileleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow configfilewrap()'s to do buffer switches
 * instead of setting up a fresh configfilein.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void configfilerestart (FILE *input_file  );
void configfile_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE configfile_create_buffer (FILE *file,int size  );
void configfile_delete_buffer (YY_BUFFER_STATE b  );
void configfile_flush_buffer (YY_BUFFER_STATE b  );
void configfilepush_buffer_state (YY_BUFFER_STATE new_buffer  );
void configfilepop_buffer_state (void );

static void configfileensure_buffer_stack (void );
static void configfile_load_buffer_state (void );
static void configfile_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER configfile_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE configfile_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE configfile_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE configfile_scan_bytes (yyconst char *bytes,int len  );

void *configfilealloc (yy_size_t  );
void *configfilerealloc (void *,yy_size_t  );
void configfilefree (void *  );

#define yy_new_buffer configfile_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        configfileensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            configfile_create_buffer(configfilein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        configfileensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            configfile_create_buffer(configfilein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define configfilewrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *configfilein = (FILE *) 0, *configfileout = (FILE *) 0;

typedef int yy_state_type;

extern int configfilelineno;

int configfilelineno = 1;

extern char *configfiletext;
#define yytext_ptr configfiletext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up configfiletext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	configfileleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[69] =
    {   0,
        0,    2,    0,    0,   27,   25,    9,    1,    8,   11,
        7,   24,   25,    5,    4,   10,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,   22,   13,   12,   26,
        0,    7,    5,    0,    6,   10,    2,    2,    2,    2,
        2,    2,    2,   22,   21,   14,   15,   19,   20,   16,
       18,   17,    0,    3,    2,    2,   14,   15,    0,    0,
        2,    2,   14,    0,    2,   23,    2,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        7,    1,    1,    4,    8,    9,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   11,   11,    7,    1,    7,
        7,    7,    1,   12,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   14,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        7,   15,    7,    1,   13,    1,   13,   16,   13,   13,

       13,   17,   13,   13,   13,   13,   13,   13,   13,   18,
       13,   13,   13,   19,   13,   20,   13,   13,   13,   13,
       13,   13,    7,    1,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[21] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    4,    4,
        4,    1,    4,    4,    3,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[78] =
    {   0,
        0,   20,   38,   39,  145,  146,  146,  146,  146,  139,
        0,  146,   35,   46,  146,    0,    0,    0,    0,  138,
        0,    0,   37,   52,    0,   66,    0,  146,  146,   77,
      137,    0,    0,   39,  146,    0,    0,  123,    0,    0,
       41,    0,    0,    0,  146,   48,   54,  146,  146,  146,
      146,  146,  122,   79,   95,   81,   91,   93,  118,  114,
      102,  110,   98,  101,   94,  146,    0,  146,  109,  113,
       65,  117,  121,  125,  129,  133,  137
    } ;

static yyconst flex_int16_t yy_def[78] =
    {   0,
       68,   68,   69,   69,   68,   68,   68,   68,   68,   68,
       70,   68,   68,   68,   68,   71,   72,   72,   72,   72,
       73,   72,   72,   72,   72,   68,   74,   68,   68,   75,
       68,   70,   14,   68,   68,   71,   72,   72,   73,   24,
       72,   72,   26,   74,   68,   68,   68,   68,   68,   68,
       68,   68,   76,   68,   77,   72,   68,   68,   76,   68,
       77,   72,   68,   68,   72,   68,   72,    0,   68,   68,
       68,   68,   68,   68,   68,   68,   68
    } ;

static yyconst flex_int16_t yy_nxt[167] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,    6,   14,
       14,   15,   16,   16,    6,   16,   16,   16,   16,   16,
       17,   18,    8,   19,   20,   21,   22,   23,   17,   24,
       24,   25,   26,   26,   17,   26,   26,   26,   26,   26,
       28,   28,   29,   29,   33,   33,   40,   40,   54,   54,
       56,   56,   30,   30,   34,   33,   33,   57,   58,   35,
       41,   40,   40,   58,   58,   42,   37,   37,   36,   37,
       37,   37,   37,   43,   43,   43,   43,   37,   43,   43,
       37,   43,   43,   43,   43,   43,   46,   47,   54,   54,
       56,   56,   48,   49,   50,   51,   52,   59,   67,   62,

       63,   58,   58,   58,   59,   66,   62,   58,   58,   27,
       27,   27,   27,   32,   65,   32,   32,   37,   64,   37,
       37,   39,   60,   39,   39,   44,   60,   55,   44,   45,
       45,   45,   45,   59,   59,   59,   59,   61,   61,   61,
       61,   53,   38,   31,   68,    5,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68
    } ;

static yyconst flex_int16_t yy_chk[167] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        3,    4,    3,    4,   13,   13,   23,   23,   34,   34,
       41,   41,    3,    4,   14,   14,   14,   46,   46,   14,
       24,   24,   24,   47,   47,   24,   26,   26,   71,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   30,   30,   54,   54,
       56,   56,   30,   30,   30,   30,   30,   55,   65,   55,

       57,   57,   58,   58,   61,   64,   61,   63,   63,   69,
       69,   69,   69,   70,   62,   70,   70,   72,   60,   72,
       72,   73,   59,   73,   73,   74,   53,   38,   74,   75,
       75,   75,   75,   76,   76,   76,   76,   77,   77,   77,
       77,   31,   20,   10,    5,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int configfile_flex_debug;
int configfile_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *configfiletext;
#line 1 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
#line 2 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
#include <stdio.h>
#include <string.h>
#include <configfile.h>
#define MODNAME "Configfile"
#include <kusp_common.h>
#include "configfile_yacc.h"

int lineno;
int tokenpos;
char linebuf[5000];

// FIXME; is there some way we could not use a fixed size buffer?
// yes, use open_memstream
/**
  * buffer to store characters when building string constants
  */
#define STRING_BUF_SIZE 8192
static char string_buf[STRING_BUF_SIZE];
static char *string_buf_ptr;


static struct keyword {
  char *name;
  int value;
} keywords[] = {
	{"true", TRUE},
	{"false", FALSE},
	{NULL, 0}
};

static int keyword(char *string) {
  /* loop through the keyword list, returning a value
     if the keyword was found. if it wasn't in the list
     return 0.
  */
  struct keyword *ptr = keywords;

  for(; ptr->name; ptr++)
    if (strcmp(ptr->name, string) == 0)
      return ptr->value;
  return 0;
}



#line 573 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.c"

#define INITIAL 0
#define str 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int configfilelex_destroy (void );

int configfileget_debug (void );

void configfileset_debug (int debug_flag  );

YY_EXTRA_TYPE configfileget_extra (void );

void configfileset_extra (YY_EXTRA_TYPE user_defined  );

FILE *configfileget_in (void );

void configfileset_in  (FILE * in_str  );

FILE *configfileget_out (void );

void configfileset_out  (FILE * out_str  );

int configfileget_leng (void );

char *configfileget_text (void );

int configfileget_lineno (void );

void configfileset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int configfilewrap (void );
#else
extern int configfilewrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( configfiletext, configfileleng, 1, configfileout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( configfilein )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( configfilein ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, configfilein))==0 && ferror(configfilein)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(configfilein); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int configfilelex (void);

#define YY_DECL int configfilelex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after configfiletext and configfileleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( configfileleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(configfiletext[configfileleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 57 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"

#line 761 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! configfilein )
			configfilein = stdin;

		if ( ! configfileout )
			configfileout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			configfileensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				configfile_create_buffer(configfilein,YY_BUF_SIZE );
		}

		configfile_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of configfiletext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 69 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 146 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 58 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			//printf("newline\n");
			lineno++;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			strncpy(linebuf, configfiletext, 4999);
			
			linebuf[4999] = '\0';
			//printf("text read %d:%s\n",lineno,linebuf);
			tokenpos = 0;
			yyless(0);
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			configfilelval.doubleval = atof(configfiletext);
			tokenpos += configfileleng;
			return DOUBLE;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			tokenpos += configfileleng;
			return REFERENCE;
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{	
			configfilelval.intval = atoi(configfiletext);
			tokenpos += configfileleng;
			return INTEGER;
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 84 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			char *s = strdup(configfiletext);
			// snip off the trailing L
			s[strlen(s)-1] = '\0';
			configfilelval.longval = atoll(s);
			free(s);
			tokenpos += configfileleng;
			return LONG;
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			tokenpos += configfileleng;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 96 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			tokenpos += configfileleng;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			tokenpos += configfileleng * 8;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{	
			configfilelval.cmd = keyword(configfiletext);
			tokenpos += configfileleng;
			if (configfilelval.cmd != 0) {
				return configfilelval.cmd;
			} else {
				configfilelval.string = strdup(configfiletext);
				return STRING;
			}
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{ /* opening quote for string */
			tokenpos += configfileleng;
			string_buf_ptr = string_buf; 
			BEGIN(str);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 118 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{ /* saw closing quote - all done */
        		tokenpos += configfileleng;
			BEGIN(INITIAL);
        		*string_buf_ptr = '\0';
			configfilelval.string = strdup(string_buf);
       			return STRING;
		}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 125 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			tokenpos += configfileleng;
			configfileerror("unterminated string constant");
        	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 130 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			/* octal escape sequence */
        		int result;
			(void) sscanf( configfiletext + 1, "%o", &result );

			if ( result > 0xff ) {
				configfileerror("bad escape sequence");
			} else {
                	/* error, constant is out-of-bounds */
        			*string_buf_ptr++ = result;
			}
			tokenpos += configfileleng;
        	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 143 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
        		/* generate error - bad escape sequence; something
         		 * like '\48' or '\0777777'
         		 */
			tokenpos += configfileleng;
			configfileerror("bad escape sequence");
        	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			*string_buf_ptr++ = '\n';
			tokenpos += configfileleng;
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			*string_buf_ptr++ = '\t';
			tokenpos += configfileleng;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 159 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			*string_buf_ptr++ = '\r';
			tokenpos += configfileleng;
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 163 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			*string_buf_ptr++ = '\b';
			tokenpos += configfileleng;
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 167 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
			*string_buf_ptr++ = '\f';
			tokenpos += configfileleng;
		}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 171 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{ /* anything that is escaped */
			*string_buf_ptr++ = configfiletext[1];
			tokenpos += configfileleng;
		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 175 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{
        		char *yptr = configfiletext;
        		while ( *yptr ) {
                		*string_buf_ptr++ = *yptr++;
				tokenpos++;
			}
        	}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 182 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{	
			char *v = strdup(configfiletext + 3);
			v[configfileleng-6] = '\0';
			configfilelval.string = v;
			tokenpos += configfileleng;
			return STRING;
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 189 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{	
			tokenpos += configfileleng;
			return configfiletext[0];
		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 193 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
{	
			tokenpos += configfileleng;
			configfileerror("skipping unknown text");
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 198 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"
ECHO;
	YY_BREAK
#line 1090 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed configfilein at a new source and called
			 * configfilelex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = configfilein;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( configfilewrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * configfiletext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of configfilelex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					configfilerealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			configfilerestart(configfilein  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) configfilerealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 69 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 69 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 68);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up configfiletext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					configfilerestart(configfilein );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( configfilewrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve configfiletext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void configfilerestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        configfileensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            configfile_create_buffer(configfilein,YY_BUF_SIZE );
	}

	configfile_init_buffer(YY_CURRENT_BUFFER,input_file );
	configfile_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void configfile_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		configfilepop_buffer_state();
	 *		configfilepush_buffer_state(new_buffer);
     */
	configfileensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	configfile_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (configfilewrap()) processing, but the only time this flag
	 * is looked at is after configfilewrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void configfile_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	configfilein = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE configfile_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) configfilealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in configfile_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) configfilealloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in configfile_create_buffer()" );

	b->yy_is_our_buffer = 1;

	configfile_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with configfile_create_buffer()
 * 
 */
    void configfile_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		configfilefree((void *) b->yy_ch_buf  );

	configfilefree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a configfilerestart() or at EOF.
 */
    static void configfile_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	configfile_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then configfile_init_buffer was _probably_
     * called from configfilerestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void configfile_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		configfile_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void configfilepush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	configfileensure_buffer_stack();

	/* This block is copied from configfile_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from configfile_switch_to_buffer. */
	configfile_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void configfilepop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	configfile_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		configfile_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void configfileensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)configfilealloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in configfileensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)configfilerealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in configfileensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE configfile_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) configfilealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in configfile_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	configfile_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to configfilelex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       configfile_scan_bytes() instead.
 */
YY_BUFFER_STATE configfile_scan_string (yyconst char * yystr )
{
    
	return configfile_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to configfilelex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE configfile_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) configfilealloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in configfile_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = configfile_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in configfile_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up configfiletext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		configfiletext[configfileleng] = (yy_hold_char); \
		(yy_c_buf_p) = configfiletext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		configfileleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int configfileget_lineno  (void)
{
        
    return configfilelineno;
}

/** Get the input stream.
 * 
 */
FILE *configfileget_in  (void)
{
        return configfilein;
}

/** Get the output stream.
 * 
 */
FILE *configfileget_out  (void)
{
        return configfileout;
}

/** Get the length of the current token.
 * 
 */
int configfileget_leng  (void)
{
        return configfileleng;
}

/** Get the current token.
 * 
 */

char *configfileget_text  (void)
{
        return configfiletext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void configfileset_lineno (int  line_number )
{
    
    configfilelineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see configfile_switch_to_buffer
 */
void configfileset_in (FILE *  in_str )
{
        configfilein = in_str ;
}

void configfileset_out (FILE *  out_str )
{
        configfileout = out_str ;
}

int configfileget_debug  (void)
{
        return configfile_flex_debug;
}

void configfileset_debug (int  bdebug )
{
        configfile_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from configfilelex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    configfilein = stdin;
    configfileout = stdout;
#else
    configfilein = (FILE *) 0;
    configfileout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * configfilelex_init()
     */
    return 0;
}

/* configfilelex_destroy is for both reentrant and non-reentrant scanners. */
int configfilelex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		configfile_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		configfilepop_buffer_state();
	}

	/* Destroy the stack itself. */
	configfilefree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * configfilelex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *configfilealloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *configfilerealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void configfilefree (void * ptr )
{
	free( (char *) ptr );	/* see configfilerealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 198 "/home/hhicks/workspace/kusp/trunk/subsystems/kusp-common/libkusp/configfile_lex.l"



void configfileerror(const char *s) {
	wprintf("%s at '%s' in line %d:\n",
			s, configfiletext, lineno);
	printf("%s\n", linebuf);
	printf("%*s\n", 1+tokenpos, "^\n");
}


