#!/usr/bin/env python

import sys
import pprint

f = open(sys.argv[1], "r")

ctr = 0
tab = {}
for line in f:
	items = line.split()
	if (len(items) > 1):
		name = items[1]
		tab[ctr] = (name, None)

		ctr = ctr + 1
			
pprint.pprint(tab)
