#!/usr/bin/env python

import os
import sys
from pykusp import taskalias
import optparse

name = "trace-me"

parser = optparse.OptionParser()
parser.add_option("-i","--ignore-me", action="store_true",
		dest="ignore",help="Put process in ignore set rather than trace set")
parser.set_defaults(
	ignore = False
)

(options, args) = parser.parse_args()

if options.ignore:
	name = "ignore-me"

taskalias.add_alias_track(name)



os.execvp(sys.argv[1], sys.argv[1:])

