#!/bin/bash
# Source function library.
. /etc/rc.d/init.d/functions

dskilogd=/usr/bin/dskilogd
[ -f $dskilogd ] || exit 0

config=/etc/dskilogd/dskilogd.dski
[ -f $config ] || exit 0

OPTIONS="-c $config"

RETVAL=0

# See how we were called.
case "$1" in
  start)
        echo -n "Starting dskilogd: "
        daemon $dskilogd $OPTIONS
	RETVAL=$?
        echo
        ;;
  stop)
	echo -n $"Stopping $prog: "
	if [ -n "`pidfileofproc $dskilogd`" ] ; then
	    killproc $dskilogd
	else
	    failure $"Stopping $prog"
	fi
	RETVAL=$?
        echo
        ;;
  status)
	status dskilogd
	RETVAL=$?
	;;
  restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  condrestart)
	if [ -n "`pidfileofproc $dskilogd`" ] ; then
	    $0 stop
	    $0 start
	    RETVAL=$?
	fi
	;;
  *)
        echo "Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $RETVAL
