from BoolEdit import *
#from DictEdit import *
from StrEdit import *
from FloatEdit import *
from IntEdit import *
#from ListEdit import *
from dclipboard import *
from dtab import *
from dtabbar import *
from dtabwidget import *